version: "3"
services:
  # Management
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    environment:
      TZ: '${TZ}'
      WEBPASSWORD: '${PIHOLE_WEBPASSWORD}'
      PIHOLE_DNS_: '1.1.1.1;1.0.0.1'
      FTLCONF_LOCAL_IPV4: '${PIHOLE_SERVER_ADDRESS}'
    volumes:
      - 'pihole_etc-pihole:/etc/pihole'
      - 'pihole_etc-dnsmasq.d:/etc/dnsmasq.d'
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: ${TZ}
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_LABEL_ENABLE: true
      WATCHTOWER_INCLUDE_RESTARTING: true
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:latest
    volumes:
      - uptime-kuma_config:/app/data
    ports:
      - 3001:3001
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped
  # Media Services
  jellyfin:
    container_name: jellyfin
    image: lscr.io/linuxserver/jellyfin:latest
    environment:
      TZ: '${TZ}'
      PUID: 1000
      PGID: 1000
    volumes:
      - jellyfin_config:/config
      - ${MEDIA_ROOT}/shows:/data/shows
      - ${MEDIA_ROOT}/movies:/data/movies
    ports:
      - 8096:8096
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped
  audiobookshelf:
    container_name: audiobookshelf
    image: ghcr.io/advplyr/audiobookshelf:latest
    ports:
      - 13378:80
    volumes:
      - ${MEDIA_ROOT}/audiobooks:/audiobooks
      - ${MEDIA_ROOT}/podcasts:/podcasts
      - audiobookshelf_config:/config
      - audiobookshelf_metadata:/metadata
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped
  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    environment:
      TZ: '${TZ}'
      PUID: 1000
      PGID: 1000
    volumes:
      - radarr_config:/config
      - ${MEDIA_ROOT}/movies:/movies
      - ${DOWNLOAD_ROOT}:/downloads
    ports:
      - 7878:7878
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped
  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    environment:
      TZ: '${TZ}'
      PUID: 1000
      PGID: 1000
    volumes:
      - sonarr_config:/config
      - ${MEDIA_ROOT}/shows:/shows
      - ${DOWNLOAD_ROOT}:/downloads
    ports:
      - 8989:8989
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped
  readarr:
    container_name: readarr
    image: lscr.io/linuxserver/readarr:develop
    environment:
      TZ: '${TZ}'
      PUID: 1000
      PGID: 1000
    volumes:
      - readarr_config:/config
      - ${MEDIA_ROOT}/ebooks:/ebooks
      - ${MEDIA_ROOT}/audiobooks:/audiobooks
      - ${DOWNLOAD_ROOT}:/downloads
    ports:
      - 8787:8787
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped
  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    environment:
      TZ: '${TZ}'
      PUID: 1000
      PGID: 1000
    volumes:
      - prowlarr_config:/config
    ports:
      - 9696:9696
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped
  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    environment:
      TZ: '${TZ}'
      PUID: 1000
      PGID: 1000
      WEBUI_PORT: 8080
    volumes:
      - qbittorrent_config:/config
      - ${DOWNLOAD_ROOT}:/downloads
    network_mode: service:nordlynx
    depends_on:
      - nordlynx
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped
  nordlynx:
    container_name: nordlynx
    image: ghcr.io/bubuntux/nordlynx
    cap_add:
      - NET_ADMIN
    environment:
      TZ: ${TZ}
      NET_LOCAL: ${NET_LOCAL}
      QUERY: filters\[servers_groups\]\[identifier\]=legacy_p2p
      PRIVATE_KEY: ${VPN_PRIVATE_KEY}
    ports:
      - 8080:8080
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped
volumes:
  pihole_etc-pihole:
  pihole_etc-dnsmasq.d:
  qbittorrent_config:
  prowlarr_config:
  sonarr_config:
  radarr_config:
  jellyfin_config:
  readarr_config:
  audiobookshelf_config:
  audiobookshelf_metadata:
  uptime-kuma_config: